USE [CLARITY_App_Dev]
GO

-- ===========================================
-- Create table Stage.iQueue_Clinics_Status_Board_Extract
-- ===========================================
IF EXISTS (SELECT TABLE_NAME 
	       FROM   INFORMATION_SCHEMA.TABLES
	       WHERE  TABLE_SCHEMA = N'Stage' AND
	              TABLE_NAME = N'iQueue_Clinics_Status_Board_Extract')
   DROP TABLE [Stage].[iQueue_Clinics_Status_Board_Extract]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [Stage].[iQueue_Clinics_Status_Board_Extract](
    [PAT_ENC_CSN_ID_unhashed] [NUMERIC](18,0) NOT NULL,
    [PAT_ENC_CSN_ID] [VARCHAR](256) NOT NULL,
	[PAT_MRN_ID] [VARCHAR](256) NULL,
	[DEPARTMENT_NAME] [VARCHAR](254) NULL,
	[PROV_NAME] [VARCHAR](200) NULL,
	[EVENT_DISPLAY_NAME] [VARCHAR](254) NULL,
	[INFECTION_STATUS] [VARCHAR](1200) NULL,
	[APPT_NOTES] [VARCHAR](1200) NULL,
	[EVENT_DTTM] [DATETIME] NULL,
	[VISIT_FLOW_COMMENTS] [VARCHAR](1200) NULL,
	[PRIMARY_LANGUAGE] [VARCHAR](200) NULL,
	[INTERPRETER_ASSIGNMENT] [VARCHAR](254) NULL,
	[INTERPRETER_TYPE] [VARCHAR](254) NULL,
	[INTERPRETER_VENDOR] [VARCHAR](254) NULL,
    [APPT_STATUS_NAME] [VARCHAR](254) NULL,
	[APPT_DTTM] [DATETIME] NULL,
	[APPT_LENGTH] [INT] NULL,
	[ENC_TYPE_NAME] [VARCHAR](254) NULL,
    [TIME_TO_ROOM_MINUTES] [INT] NULL,
    [TIME_IN_ROOM_MINUTES] [INT] NULL,
    [CYCLE_TIME_MINUTES] [INT] NULL,
    [ETL_guid] [VARCHAR](50) NULL,
    [Load_Dte] [SMALLDATETIME] NULL
) ON [PRIMARY]
GO


