USE [CLARITY_App_Dev]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [Stage].[iQueue_Clinics_Extract](
    [PAT_ENC_CSN_ID_unhashed] [NUMERIC](18,0) PRIMARY KEY NOT NULL,
    [PAT_ENC_CSN_ID] [VARCHAR](256) NOT NULL,
	[PAT_MRN_ID] [VARCHAR](256) NULL,
	[DEPARTMENT_NAME] [VARCHAR](254) NULL,
	[DEPT_SPECIALTY_NAME] [VARCHAR](254) NULL,
	[PROV_ID] [VARCHAR](18) NULL,
	[PROV_NAME] [VARCHAR](200) NULL,
	[APPT_DTTM] [DATETIME] NULL,
    [ENC_REASON_NAME] [VARCHAR](1200) NULL,
	[APPT_NOTES] [VARCHAR](1200) NULL,
	[PRC_NAME] [VARCHAR](254) NULL,
	[APPT_LENGTH] [INT] NULL,
    [APPT_STATUS_NAME] [VARCHAR](254) NULL,
	[APPT_MADE_DTTM] [DATETIME] NULL,
    [APPT_CANC_DTTM] [DATETIME] NULL,
    [UPDATE_DATE] [DATETIME] NULL,
    [SIGNIN_DTTM] [DATETIME] NULL,
    [BEGIN_CHECKIN_DTTM] [DATETIME] NULL,
    [CHECKIN_DTTM] [DATETIME] NULL,
    [Patient_Room] [VARCHAR](1200) NULL,
	[Patient_Room_Recorded_DtTm] [VARCHAR](1200) NULL,
	[Patient_Track] [VARCHAR](1200) NULL,
	[Patient_Track_Recorded_DtTm] [VARCHAR](1200) NULL,
	[ARVL_LIST_REMOVE_DTTM] [DATETIME] NULL,
    [AMB PATIENT VERIFIED] [DATETIME] NULL,
    [UVA AMB VITALS SIMPLE] [DATETIME] NULL,
    [ROOMED_DTTM] [DATETIME] NULL,
    [NURSE_LEAVE_DTTM] [DATETIME] NULL,
    [PHYS_ENTER_DTTM] [DATETIME] NULL,
    [T UVA AMB PATIENT UNDERSTANDING AVS] [DATETIME] NULL,
    [VISIT_END_DTTM] [DATETIME] NULL,
    [CHECKOUT_DTTM] [DATETIME] NULL,
    [TIME_TO_ROOM_MINUTES] [INT] NULL,
    [TIME_IN_ROOM_MINUTES] [INT] NULL,
    [CYCLE_TIME_MINUTES] [INT] NULL,
    [ETL_guid] [VARCHAR](50) NULL,
    [Load_Dte] [SMALLDATETIME] NULL
	) ON [PRIMARY]
GO


